{
 "title": "App Overview",
 "panels": [
  {
   "title": "Go GC Pauses (ms)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 4 },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum[5m])) / sum(rate(go_gc_duration_seconds_count[5m])) * 1000"
    }
   ]
  },
  {
   "title": "Process CPU Seconds",
   "type": "graph",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "targets": [
    { "expr": "go_goroutines" }
   ]
  }
 ]
}