name: CI - Go Domain Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go-domain-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run domain unit tests with coverage
        run: go test -v -cover ./internal/domain/...
